### ISSUE TITLE
ERROR: Exception: Traceback - FossaPup64

### ISSUE THREAD

**Issue by RessBB** [Sl-Sanda-Ru/Temp-SMS-Receive#2]
root# python3 -m pip install requirements.txt
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 305, in run
    session = self.get_default_session(options)
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/req_command.py", line 74, in get_default_session
    self._session = self.enter_context(self._build_session(options))
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/req_command.py", line 84, in _build_session
    session = PipSession(
  File "/usr/lib/python3/dist-packages/pip/_internal/network/session.py", line 241, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/usr/lib/python3/dist-packages/pip/_internal/network/session.py", line 132, in user_agent
    zip(["name", "version", "id"], distro.linux_distribution()),
  File "/usr/share/python-wheels/distro-1.4.0-py2.py3-none-any.whl/distro.py", line 122, in linux_distribution
    return _distro.linux_distribution(full_distribution_name)
  File "/usr/share/python-wheels/distro-1.4.0-py2.py3-none-any.whl/distro.py", line 677, in linux_distribution
    self.version(),
  File "/usr/share/python-wheels/distro-1.4.0-py2.py3-none-any.whl/distro.py", line 737, in version
    self.lsb_release_attr('release'),
  File "/usr/share/python-wheels/distro-1.4.0-py2.py3-none-any.whl/distro.py", line 899, in lsb_release_attr
    return self._lsb_release_info.get(attribute, '')
  File "/usr/share/python-wheels/distro-1.4.0-py2.py3-none-any.whl/distro.py", line 552, in __get__
    ret = obj.__dict__[self._fname] = self._f(obj)
  File "/usr/share/python-wheels/distro-1.4.0-py2.py3-none-any.whl/distro.py", line 1012, in _lsb_release_info
    stdout = subprocess.check_output(cmd, stderr=devnull)
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('lsb_release', '-a')' returned non-zero exit status 1.
root# pip3 install requirements.txt
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 305, in run
    session = self.get_default_session(options)
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/req_command.py", line 74, in get_default_session
    self._session = self.enter_context(self._build_session(options))
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/req_command.py", line 84, in _build_session
    session = PipSession(
  File "/usr/lib/python3/dist-packages/pip/_internal/network/session.py", line 241, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/usr/lib/python3/dist-packages/pip/_internal/network/session.py", line 132, in user_agent
    zip(["name", "version", "id"], distro.linux_distribution()),
  File "/usr/share/python-wheels/distro-1.4.0-py2.py3-none-any.whl/distro.py", line 122, in linux_distribution
    return _distro.linux_distribution(full_distribution_name)
  File "/usr/share/python-wheels/distro-1.4.0-py2.py3-none-any.whl/distro.py", line 677, in linux_distribution
    self.version(),
  File "/usr/share/python-wheels/distro-1.4.0-py2.py3-none-any.whl/distro.py", line 737, in version
    self.lsb_release_attr('release'),
  File "/usr/share/python-wheels/distro-1.4.0-py2.py3-none-any.whl/distro.py", line 899, in lsb_release_attr
    return self._lsb_release_info.get(attribute, '')
  File "/usr/share/python-wheels/distro-1.4.0-py2.py3-none-any.whl/distro.py", line 552, in __get__
    ret = obj.__dict__[self._fname] = self._f(obj)
  File "/usr/share/python-wheels/distro-1.4.0-py2.py3-none-any.whl/distro.py", line 1012, in _lsb_release_info
    stdout = subprocess.check_output(cmd, stderr=devnull)
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('lsb_release', '-a')' returned non-zero exit status 1.
root# python3 tempsms.py
[!] Something Error Occured While Installing Dependencies
 Maybe Pip Isn'T Installed Or Requirements.Txt File Not Available?

**Comment by Sl-Sanda-Ru** [comment]
Hello mate, try it on a virtual environment [https://www.freecodecamp.org/news/how-to-setup-virtual-environments-in-python/](url)

**Comment by RessBB** [comment]
Thanks Sl-Sanda-Ru, I'll give it a try, I think it should work.

Odesláno z bezpečného [Proton Mailu](https://proton.me/).

pátek, 19. dubna 2024 v 8:37, Sandaru Ashen Fernando ***@***.***> napsal/a:

**Comment by RessBB** [comment]
Yes, the virtual environment works very well. Thanks to you, I managed to get the application up and running. Now I'm trying to verify my account on FB with the application, do you have any experience or recommendations?

For now, I tried many numbers but FB filters them to a great extent, so I was not successful yet, moreover, with a large number of verification requests, you have to wait 24 hours.
